(function () {
  const places = [
    "mouth", "neck", "jaw", "throat", "collarbone", "shoulder", "chest", "ribs",
    "stomach", "waist", "hip", "lower back", "wrist", "palm", "ear", "shoulder blade",
    "sternum", "hip bone", "temple", "cheek", "thigh", "knee", "hair", "knuckles",
    "ankle", "calf", "forearm", "the small of the back"
  ];
  const limits = [
    "Stop the moment they tap you.",
    "They can refuse before you begin.",
    "Only if they nod.",
    "Ten seconds, then you stop.",
    "End it while you still want more.",
    "They say stay, or they say enough.",
    "Hands stay over clothes unless they move them.",
    "You do not go further than this one thing.",
    "If they go quiet, you ask before you continue.",
    "They lead the pace.",
    "One try. Then you look at them and wait.",
    "Either of you can stop it in the middle."
  ];
  const dareFrames = [
    function (p, lim) { return "Kiss their " + p + ". " + lim; },
    function (p, lim) { return "Put your open hand on their " + p + ", over clothes. " + lim; },
    function (p, lim) { return "Put your mouth near their " + p + " and do not touch until they say you can. " + lim; },
    function (p, lim) { return "Tell them exactly what you want done to their " + p + ". " + lim; },
    function (p, lim) { return "Let them move your hand to their " + p + ". Leave it if they leave it. " + lim; },
    function (p, lim) { return "Trace their " + p + " with one finger. Over clothes if it is covered. " + lim; },
    function (p, lim) { return "Ask if you may use your mouth on their " + p + ". Accept the answer. " + lim; },
    function (p, lim) { return "Hold their " + p + " while you kiss their mouth. " + lim; },
    function (p, lim) { return "Say how you want their " + p + " touched. Then let them do it, or refuse. " + lim; },
    function (p, lim) { return "Press close so your body meets their " + p + ". No hands under clothes. " + lim; },
    function (p, lim) { return "Kiss their " + p + " once, slowly, and ask for a second. " + lim; },
    function (p, lim) { return "Describe what your mouth would do at their " + p + ". Then wait. " + lim; },
    function (p, lim) { return "They may put your mouth on their " + p + ", or they may not. " + lim; },
    function (p, lim) { return "Undo one thing that covers their " + p + ", or leave it covered. Their choice. " + lim; },
    function (p, lim) { return "Stay still while they decide whether to kiss your " + p + ". " + lim; },
    function (p, lim) { return "Whisper a dare about their " + p + " that you were not going to say. " + lim; }
  ];
  const truthFrames = [
    function (p, lim) { return "How do you want their mouth on your " + p + ". Say it plainly. " + lim; },
    function (p, lim) { return "What do you want their hands to do at your " + p + ". " + lim; },
    function (p, lim) { return "Would you let them undress your " + p + " first. Yes, no, or not yet. " + lim; },
    function (p, lim) { return "Tell them the sentence you think when you picture their " + p + ". " + lim; },
    function (p, lim) { return "Do you want their " + p + " closer, or do you want yours against it. Choose. " + lim; },
    function (p, lim) { return "What should they not do to your " + p + " unless you ask twice. " + lim; },
    function (p, lim) { return "Name the pace you want on your " + p + ". Slow, or greedy. " + lim; },
    function (p, lim) { return "Tell them if your " + p + " is a place you are shy about. " + lim; },
    function (p, lim) { return "What sound do you want to make if they kiss your " + p + ". " + lim; },
    function (p, lim) { return "Who should lead if the next thing happens at your " + p + ". " + lim; },
    function (p, lim) { return "Say whether you want marks on your " + p + ", and where, or say you don’t. " + lim; },
    function (p, lim) { return "What would you whisper if their mouth stayed on your " + p + ". " + lim; }
  ];
  const wildDares = [
    "Straddle them, clothes on. Move once. Then stop and look at them.",
    "Take their hand and slide it under your shirt. They can pull it back.",
    "Kiss them as if you mean to start something, then ask before you continue.",
    "Put your mouth on their stomach, over clothes, and say what you want lower.",
    "Unbutton one thing of theirs. Wait. They name the next button, or they say stop.",
    "Grind against them slowly for five breaths. Hands stay where they put them.",
    "Let them take one thing off you. You don’t help, and you don’t rush them.",
    "Whisper exactly where you want their tongue. Then let them decide.",
    "Stay standing. They may touch you anywhere over clothes until you say more, or stop.",
    "Kiss down their neck. Don’t reach their chest unless they pull you there.",
    "Take off your shirt, or theirs. Their choice. Then kiss them.",
    "Sit in their lap, facing them. Rock once. Ask if they want another.",
    "Use your mouth on their fingers. Look at them while you do it.",
    "In their ear, describe the next thing you want in this room. Do only the first step.",
    "Let them put a hand between your legs, over clothes. You say when it moves.",
    "Hold their hips and kiss them until one of you makes a sound. Then stop.",
    "They pick a place. You kiss it. If they want your mouth to stay, they have to say stay.",
    "Undo their waistband, or one button, and leave it like that.",
    "Lie back. They kiss whatever they want above your waist. Your hands stay in your hair.",
    "Say the most direct request you have. They answer yes, no, or not yet.",
    "Kneel between their knees, or sit there. Don’t touch until they touch you.",
    "Let them watch you take one thing off. They don’t get to help.",
    "Put their hand on your chest, under the shirt, and keep your hand over theirs.",
    "Kiss the inside of their thigh, over clothes, and ask if you may stay.",
    "Trade underwear for a dare they were going to skip. They can refuse the trade.",
    "Hold still while they kiss your mouth and your neck. Two taps ends it.",
    "Tell them to sit on you. Clothes stay on until both of you agree otherwise.",
    "Use one finger along their waistband. Don’t go under it unless they guide you.",
    "Say what you want them to do with their mouth. Then count to five so they can refuse.",
    "Let them choose: your shirt comes off, or theirs does. One of them. Not both.",
    "Press your hips to theirs and don’t kiss. See who breaks.",
    "They name a piece of clothing. You remove it from yourself, or you say no.",
    "Kiss them with your hands behind your back. They can put your hands where they want.",
    "Describe how you want to be undressed. They may do the first step only.",
    "Put your mouth at their ear and tell them the pace you want. Then match it, or don’t start.",
    "Lie on your side, facing them. One of you may put a leg over the other. Clothes on.",
    "Let them unhook, untie, or unbutton one thing. They stop after that one.",
    "Ask them to say what they want done to them. Do the smallest version of it.",
    "Keep eye contact while you touch them over clothes, low on the stomach. Stop if they look away and don’t come back.",
    "Give them your wrist. They decide where that hand goes, over clothes.",
    "Kiss their chest through the cloth. Ask before you move the cloth.",
    "Tell them to hold your face and kiss you until you forget the next rule. Then remember it and stop.",
    "Sit on the edge of something. They stand between your knees. Nobody’s hands go under clothes yet.",
    "Say the word you want them to use for what you want. Then let them use it, or not.",
    "Let them take your hand and show you the pressure they want. Copy it once.",
    "Whisper a yes-or-no question about their mouth. A kiss means yes. A headshake means no.",
    "Turn around. They may kiss the back of your neck and stop at your shoulders.",
    "Name an item you are willing to lose. Take it off yourself, slowly.",
    "They get thirty seconds to touch you over clothes wherever they have wanted to. Then the thirty seconds end.",
    "Ask if they want your mouth lower than your last kiss. Wait for the whole answer.",
    "Hold their jaw. Kiss them once like a question. They answer with a second kiss or with nothing.",
    "Put both their hands on your waist, under the hem, on skin. They can move them back out.",
    "Tell them the position you want, in one sentence. Try only the beginning of it.",
    "Let them decide if the next kiss is soft or hungry. You take that and nothing more.",
    "Slide a hand into their back pocket, or onto their hip. Ask which before you choose wrong.",
    "Say what you want to hear while they touch you. They can say it, or they can touch you in silence.",
    "Lie back and let them kiss down from your mouth. They stop where you tap.",
    "Take their shirt in your fist. Don’t take it off. Tell them what you would do if you did.",
    "Offer your neck. They choose how long their mouth stays.",
    "Tell them to say stop once, so you both hear it work. Then start again only if they say go.",
    "Put your forehead on theirs. Say the dirtiest true thing you can in a whisper.",
    "Let them straddle you. Clothes on. Their hands may go under your shirt, or not. They choose.",
    "Kiss their hip over clothes and keep your hands flat on the bed, or the floor, or their knees.",
    "Ask them to show you, with your hand, how they want to be touched. Over clothes first.",
    "Unfasten one thing of your own and leave it open. Their move, or no move.",
    "Say whether you want to be the one on top. If yes, get there. If no, pull them there.",
    "Keep your mouth on theirs while one hand stays still on their ribs, under the cloth, if they nod.",
    "Tell them a place you want licked, not kissed. They may do it, or they may kiss it instead.",
    "Give them one minute in your lap. They set the pace. You can end the minute early.",
    "Take off one sock, one layer, or one piece of jewelry, and make them watch. They pick which kind.",
    "Ask what they want your tongue to do. Repeat it back. Then ask if they meant it.",
    "Stand behind them and fit your body to theirs. Your hands stay on their waist until they move them.",
    "Let them put a hand over your mouth, gently, and kiss your neck. You can pull the hand away.",
    "Say the sentence you would only say if you were already undressed. Stay dressed while you say it.",
    "They choose a hand. You put that hand between your legs, over clothes, and you decide if it stays.",
    "Kiss them and don’t let either of you talk for five breaths. Then one of you has to ask for more.",
    "Tell them to take something off you with one hand. You can catch their wrist.",
    "Lie between their legs, clothes on, and do not grind until they say you can.",
    "Offer two options: your mouth on their neck, or their mouth on yours. They pick, and it happens once.",
    "Put your thumb on their lower lip. They decide whether that becomes a kiss.",
    "Say how wet, or how hard, you are willing to admit you are. One sentence. Then kiss them.",
    "Let them open your knees with their hands. Clothes stay on. They stop if your knees don’t go.",
    "Whisper what you want them to beg for. They don’t have to beg.",
    "Hold the hem of their shirt. Ask, out loud, if it comes off. Live with the answer.",
    "Kiss their chest, then their stomach, then stop and ask if the next kiss is allowed.",
    "They name the pressure: light, or firm. You touch them over clothes that way, low on the hip.",
    "Tell them you will do one thing they have wanted. They have to say it. You may still say no.",
    "Sit facing them with your legs over theirs. Rock until one of you laughs or one of you says don’t stop. Then stop anyway and ask.",
    "Let them kiss you while you keep your hands off them. They may guide your hands back.",
    "Say the act you want next, using the plain word. Then do not do it until they repeat the word.",
    "Take their hand under your waistband and stop at the edge. They cross it, or they don’t.",
    "Give them your collar, or your neckline, in your fist. They pull you in, or they let go.",
    "Tell them where you want to be kissed for a full minute. Time it. They can quit early.",
    "Lie on them, full length, clothes on. Neither of you moves your hands for five breaths.",
    "Ask if they want teeth. If they do, one careful bite where they point, then a kiss on it.",
    "Put your mouth on their ear and say what you want to happen to your clothes. Wait.",
    "They get to move one piece of clothing aside, not off. They choose the piece.",
    "Say whether you want to finish, or you want to be kept wanting. Then kiss them accordingly, and stop.",
    "Let them stand over you while you sit. They decide if you kiss them, or if they kiss you first.",
    "Trace the line of their underwear with a finger, on top of the clothes. Don’t go under.",
    "Tell them the last dare you hope comes up. Then offer to do it now. They can save it.",
    "Hold their belt loops or their hips and pull them in one inch. Ask before the second inch.",
    "Kiss with an open mouth, once. Break it. Ask if they want that again, slower.",
    "Let them choose the room’s light: dimmer, or leave it. Then take one thing off in that light.",
    "Say what you want their weight to feel like. They may give you some of it, clothes on.",
    "Put a hand on the inside of their knee and leave it there until they move it up, or move it off.",
    "Tell them to use you for one kiss wherever they have been thinking about. One kiss.",
    "Undo enough to show one new inch of skin. Theirs or yours. They point.",
    "Ask them to say please for the next thing. If they won’t, you don’t do it. If they will, you still may stop.",
    "Breathe them in at the neck and tell them what it does to you. Then keep your hands visible.",
    "They pick: straddling, or being straddled. Clothes on. Ten seconds of movement, then still.",
    "Say the filthiest polite version of what you want, then the plain version. They choose which one you are allowed to start."
  ];
  const wildTruths = [
    "Where do you want their mouth that you have not named out loud.",
    "Tell them how you want to be touched under your clothes. They don’t have to do it.",
    "Say, plainly, what your body is doing right now because they are this close.",
    "Describe the last time you wanted them and did nothing about it.",
    "What would you let them take off you if they asked in the next minute.",
    "Name the sound you want out of them.",
    "Do you want their hands slow, or do you want them greedy. Choose.",
    "Tell them something you would allow only if the door is shut.",
    "What do you picture when you want them and you are alone.",
    "Say whether you want to be the one on top.",
    "Tell them the most direct sentence you can manage without looking away.",
    "Where do you want their tongue. Say the place.",
    "What are you willing to ask for twice.",
    "Tell them what enough sounds like, and what more sounds like.",
    "Do you want to be watched while you take something off. Yes or no.",
    "Which piece of clothing do you want their hands on first.",
    "Admit the dare you hope they give you.",
    "How long do you want their mouth on you. Give a number, or say until I stop you.",
    "Do you want marks. Where. Or say you don’t.",
    "What do you want them to do while you stay still.",
    "Tell them the pace that actually works for you.",
    "What word do you want them to say in your ear.",
    "Are you more undone by their mouth or by their hands. Choose, and say where.",
    "What do you want permission to do to them tonight.",
    "Tell them a yes you have been postponing.",
    "What should they take off you, and what should stay on.",
    "Say the part of them you think about when you shouldn’t.",
    "Do you want to be asked, or do you want them to tell you. Pick one.",
    "What would you let them see if the light stayed on.",
    "Tell them where you are shy, and where you are not.",
    "What do you want to hear yourself say.",
    "Name the thing you want their weight to do.",
    "How close are you to asking them to go under your clothes. Say it as a number.",
    "What do you want them to beg for, if anything.",
    "Tell them the kiss you want next, in detail, including where it ends.",
    "Do you want their hand between your legs. Over clothes, or not at all, or you tell them.",
    "What is the smallest thing they could do that would wreck you.",
    "Say whether you want to finish, or be kept wanting.",
    "What outfit, or lack of one, do you want them in. One sentence.",
    "Tell them who should set the pace for the next ten minutes.",
    "Where do you want to be kissed for longer than is polite.",
    "What are you hoping they dare you to take off.",
    "Say the plain word for what you want. Not a euphemism.",
    "Do you want their mouth on your chest. Yes, no, or later.",
    "Tell them a rule you want for the next few minutes.",
    "What do you want done to your throat, if anything. Kiss, hand, or nothing.",
    "Are you willing to ask them to sit on you. Ask, or say you won’t.",
    "Tell them what you want their tongue to do, and what you don’t.",
    "What would make you say don’t stop.",
    "Say the place you want their hips.",
    "Do you want to undress them, or be undressed. Choose.",
    "Tell them the thought you cut off when other people are in the room.",
    "How do you want to be held down, if you do. Hands, weight, or not at all.",
    "What do you want them to look at while you kiss them.",
    "Say if you want the next step to happen standing, or lying down.",
    "What are you wearing that you want their hands under.",
    "Tell them the question you are afraid they will ask, then let them ask a different one.",
    "Do you want teeth anywhere. Say where, or say no.",
    "What should they repeat until you believe they mean it.",
    "Name the minute you started wanting them today.",
    "Tell them whether you want to be quiet, or you want to be heard.",
    "What do you want to do with their waistband.",
    "Say the favor you want from their mouth.",
    "Do you want to be in their lap. Say it as a request, or don’t.",
    "Tell them what ‘not yet’ should protect.",
    "Where should their hands be if you kiss them right now.",
    "What do you want taken off them. Be specific, and let them veto it.",
    "Say how you want the night to tip from this into more.",
    "Tell them the dirtiest thing you are willing to repeat if they ask you to say it again.",
    "Do you want their fingers in your mouth. Yes or no.",
    "What part of this do you want slower than they think.",
    "Say who is allowed to start the next undressing.",
    "Tell them a boundary you like, because it makes the rest hotter.",
    "What do you want them to do the moment you say please.",
    "Are you closer to pulling them in, or to being pulled. Say which.",
    "Tell them the truth about how little clothing you wish was in the way.",
    "What do you want whispered against your skin.",
    "Say the thing you want their hand to find.",
    "Do you want to keep talking, or do you want the next minute silent and physical. Choose.",
    "Tell them how you want to be kissed when they are no longer being careful.",
    "What would you let them ask for that you would still want to hear.",
    "Name the inch of you that you want their attention on.",
    "Say whether you want to lead the next dare, or survive it.",
    "Tell them what you want left unfinished.",
    "What do you want them to confess back to you. Ask for that kind of truth."
  ];
  const askExtra = [
    "What do you want their mouth to finish that a kiss only starts.",
    "Over clothes, or under. Choose for the next touch.",
    "Tell them the request you would make if you were braver.",
    "Where should their hands be while you answer this.",
    "Do you want to be looked at. Say for how long.",
    "What comes off next, if anything does.",
    "Slow down, or don’t. Tell them which you actually want.",
    "What would you let them say in front of a mirror.",
    "Name a yes that expires if they wait too long. Or say none do.",
    "Who is in charge for one minute, and what are they allowed.",
    "What do you want to feel through the cloth.",
    "Tell them the kiss you keep editing in your head.",
    "Standing, or down. Where do you want the next thing.",
    "What word should stop everything, and what word should start it again.",
    "How close do you want their weight.",
    "Say the place you want warmed by their mouth.",
    "Do you want them to ask more, or to do the thing you already said.",
    "What are you wearing that is in the way.",
    "Tell them a dare you would not skip.",
    "Light on your face, or off it. Choose before the next kiss.",
    "What do you want them to take their time with.",
    "Say if you want to be teased, or taken at your word.",
    "Where do you want their attention when your eyes close.",
    "What should they do with a yes.",
    "Tell them the smallest order you would follow.",
    "Do you want your back to them, or your mouth. Pick.",
    "What are you willing to repeat until they believe you.",
    "Name the hand. Left or right. Say what it should do.",
    "How do you want to be undone without being rushed.",
    "What do you want kept on, on purpose.",
    "Tell them the truth you would trade for a dare.",
    "Do you want them closer by an inch, or by their whole body.",
    "What should happen to your shirt.",
    "Say the sound you don’t want to hold in.",
    "Where do you want the next ten seconds spent.",
    "Tell them what you want permission for.",
    "Soft, or not soft. Choose for the next kiss.",
    "What do you want them to notice with their hands.",
    "Are you asking, or are you offering. Say which this is.",
    "What do you want their hips to do, if anything.",
    "Tell them a line you want said against your throat.",
    "Do you want to be still, or do you want to be moved.",
    "What is the next honest thing your body wants.",
    "Name the boundary that makes the rest feel safe enough to want.",
    "How do you want to be held at the waist.",
    "What would you like them to take from you. A kiss, a layer, or a confession.",
    "Say the room you wish you were in, then deal with this one.",
    "Do you want their mouth to stay polite. Yes or no.",
    "What should they do if you go quiet.",
    "Tell them the touch you have been rationing.",
    "Who kisses lower first, if anyone does.",
    "What do you want said before a hand goes under cloth.",
    "Give them a number of kisses. Say where the last one lands.",
    "Do you want to be the one who says please.",
    "What part of them do you want under your mouth.",
    "Tell them how you want the wanting to show.",
    "Clothes stay, or one thing goes. You call it.",
    "What do you want them to do with your hair, or your jaw, or your hips.",
    "Say the favor. Plainly.",
    "Do you want eye contact while they touch you.",
    "What would make this minute dirtier without going further than you mean.",
    "Tell them where you want to be greedy.",
    "How should they ask for your mouth.",
    "What do you want undone, literally.",
    "Say if you want to hear them, or feel them, more.",
    "Where do you want their thumb.",
    "Tell them the pace of the hand you want.",
    "Do you want to be crowded against something. Yes or no, and what.",
    "What confession would you trade for their shirt.",
    "Name the kiss that would make you forget the game.",
    "What do you want them to risk asking.",
    "Tell them how you like to be wanted. Specific.",
    "Should the next thing be a question or a dare. You decide, then give it.",
    "Where are you willing to be kissed in this light.",
    "What do you want their voice to do to you.",
    "Say the inch you want closed.",
    "Do you want them to lead with their mouth or with their hands.",
    "What should stay a secret from everyone who is not in this room.",
    "Tell them the touch you want repeated.",
    "How bare are you willing to be for the next dare. Name the limit.",
    "What do you want them to learn about you in one minute.",
    "Say the thing you want done last, so they know not to rush to it."
  ];
  const passMore = [
    "The holder names a game on this page they have not opened. The next person has to say why they would.",
    "One sentence about the gold on this page. Then pass it.",
    "Point at someone who has not had a turn. They choose the next game, or they pass the choice on.",
    "Everyone adds one word to a sentence that must end with her name. Abigail Horlali Fiawoo.",
    "The holder reads the line at the top of the page, then says nothing else. Pass.",
    "Two people describe the same photograph without looking at it. The others say who was closer.",
    "Count backwards from sixteen. One number each. A clash starts you again.",
    "The quietest person in the last minute gets the phone and a sincere sentence, aimed at the room.",
    "Name a reason to come back to this page tomorrow. Four words. No repeats of the last answer.",
    "The holder picks Oware, the lights, or pairs. The group plays one turn, then this resumes.",
    "Say the date out loud. 16 October. The next person says who it belongs to.",
    "Trade seats. The phone goes to the seat, not the person.",
    "One true thing about the room you are in. Not about a person. Then pass.",
    "The holder asks for a number between one and sixteen. That many people say a single word.",
    "Read the colophon. Edition 01. Then someone else has to say what they would put in edition 02. No biography. A wish for the page.",
    "Hum nothing. The holder keeps a rhythm with a finger. Pass when someone joins it.",
    "The person who arrived last chooses: stay in this game, or open the letter.",
    "One compliment that is not about a face. Then the phone moves left.",
    "Everyone taps the table once if they have laughed tonight. The holder counts. Pass.",
    "Say Kofi Asante’s name as the person who made the page, then hand it to someone who has not held it.",
    "The holder closes their eyes. The others point to who should speak next. Majority takes the phone.",
    "A rule for the next round, made of five words. The next holder has to keep it.",
    "Name the hour. Someone else says what this page should feel like at that hour.",
    "The holder picks a mark on the page, lit or not, and invents nothing. They only say the number.",
    "Pass to the person who can explain Oware in one breath. If nobody can, the holder has to try.",
    "One thing in the room that is the color of the type. Then pass.",
    "The group decides, with nods, who is looking after the phone for the next three prompts.",
    "Say the overture’s idea without quoting it: some moments are for keeping. Then pass.",
    "The holder chooses someone to read Abigail’s name in full. That person does, then keeps the phone.",
    "End a lap by opening any game for one minute, then come back and continue."
  ];

  function build(frames, limitList) {
    const out = [];
    for (let i = 0; i < places.length; i++) {
      for (let f = 0; f < frames.length; f++) {
        out.push(frames[f](places[i], limitList[(i * 3 + f) % limitList.length]));
      }
    }
    return out;
  }
  function unique(list) {
    const seen = {};
    const out = [];
    list.forEach(function (line) {
      const text = String(line || "").replace(/\s+/g, " ").trim();
      if (!text || seen[text]) return;
      seen[text] = true;
      out.push(text);
    });
    return out;
  }

  const askFrames = [
    function (p) { return "What do you want them to do to your " + p + ", if you want anything."; },
    function (p) { return "Should their mouth go to your " + p + ". Yes, no, or later."; },
    function (p) { return "Tell them the pace you want on your " + p + "."; },
    function (p) { return "Is your " + p + " in bounds. Say yes, no, or not yet."; },
    function (p) { return "What should they ask before they touch your " + p + "."; },
    function (p) { return "Who decides what happens at your " + p + "."; },
    function (p) { return "Do you want their attention on your " + p + " in this light."; },
    function (p) { return "Say the request, if you have one, about your " + p + "."; }
  ];
  function buildAsk() {
    const out = [];
    for (let i = 0; i < places.length; i++) {
      for (let f = 0; f < askFrames.length; f++) out.push(askFrames[f](places[i]));
    }
    return out;
  }
  const dares = unique(wildDares.concat(build(dareFrames, limits)));
  const truths = unique(wildTruths.concat(build(truthFrames, [
    "You don’t have to demonstrate it.",
    "One sentence. Then you may stop.",
    "They don’t get to guess. You have to say it.",
    "Look at them while you answer.",
    "If you won’t say it, say the closest true thing.",
    "No joke in the middle of it.",
    "They may ask you to repeat one word.",
    "Answer, then let the phone move."
  ])));

  window.AbigailLong = {
    truths: truths,
    dares: dares,
    ask: unique(askExtra.concat(buildAsk())),
    pass: passMore
  };
})();
